#ifndef UCI_SIM_SPEC_H
#define UCI_SIM_SPEC_H

#include <stddef.h>
#include <stdint.h>

#define UCI_SIM_HEADER_SIZE 4U
#define UCI_SIM_MAX_PAYLOAD 1024U
#define UCI_SIM_MAX_PACKET (UCI_SIM_HEADER_SIZE + UCI_SIM_MAX_PAYLOAD)
#define UCI_SIM_MAX_SESSIONS 8U
#define UCI_SIM_MAX_MULTICAST_ENTRIES 8U
#define UCI_SIM_MAX_LOGICAL_LINKS 8U
#define UCI_SIM_MAX_DT_ROUNDS 32U

enum {
    UCI_MT_DATA = 0x0,
    UCI_MT_COMMAND = 0x1,
    UCI_MT_RESPONSE = 0x2,
    UCI_MT_NOTIFICATION = 0x3
};

enum {
    UCI_DATA_PACKET_FORMAT_SEND = 0x01
};

enum {
    UCI_PBF_COMPLETE = 0x0,
    UCI_PBF_NOT_COMPLETE = 0x1
};

enum {
    UCI_GID_CORE = 0x00,
    UCI_GID_SESSION_CONFIG = 0x01,
    UCI_GID_SESSION_CONTROL = 0x02,
    UCI_GID_QORVO_EXT2 = 0x0B,
    UCI_GID_QORVO_MAC = 0x0E
};

enum {
    UCI_STATUS_OK = 0x00,
    UCI_STATUS_REJECTED = 0x01,
    UCI_STATUS_FAILED = 0x02,
    UCI_STATUS_SYNTAX_ERROR = 0x03,
    UCI_STATUS_INVALID_PARAM = 0x04,
    UCI_STATUS_INVALID_RANGE = 0x05,
    UCI_STATUS_INVALID_MSG_SIZE = 0x06,
    UCI_STATUS_UNKNOWN_GID = 0x07,
    UCI_STATUS_UNKNOWN_OID = 0x08,
    UCI_STATUS_MULTICAST_LIST_FULL = 0x17,
    UCI_STATUS_ADDRESS_NOT_FOUND = 0x18,
    UCI_STATUS_ADDRESS_ALREADY_PRESENT = 0x19
};

enum {
    UCI_CORE_DEVICE_RESET = 0x00,
    UCI_CORE_DEVICE_STATUS_NTF = 0x01,
    UCI_CORE_DEVICE_INFO = 0x02,
    UCI_CORE_GET_CAPS_INFO = 0x03,
    UCI_CORE_SET_CONFIG = 0x04,
    UCI_CORE_GET_CONFIG = 0x05,
    UCI_CORE_GENERIC_ERROR = 0x07,
    UCI_CORE_QUERY_UWBS_TIMESTAMP = 0x08
};

enum {
    UCI_OID_QORVO_CORE_GET_DEVICE_STATS = 0x27
};

enum {
    UCI_OID_QORVO_MAC_SET_CALIBRATIONS = 0x2A,
    UCI_OID_QORVO_MAC_GET_CALIBRATIONS = 0x2B
};

enum {
    UCI_SESSION_INIT = 0x00,
    UCI_SESSION_DEINIT = 0x01,
    UCI_SESSION_STATUS_NTF = 0x02,
    UCI_SESSION_SET_APP_CONFIG = 0x03,
    UCI_SESSION_GET_APP_CONFIG = 0x04,
    UCI_SESSION_GET_COUNT = 0x05,
    UCI_SESSION_GET_STATE = 0x06,
    UCI_SESSION_UPDATE_CONTROLLER_MULTICAST_LIST = 0x07,
    UCI_SESSION_UPDATE_DT_ANCHOR_RANGING_ROUNDS = 0x08,
    UCI_SESSION_UPDATE_DT_TAG_RANGING_ROUNDS = 0x09,
    UCI_SESSION_DATA_TRANSFER_PHASE_CONFIG = 0x0E,
    UCI_SESSION_QUERY_DATA_SIZE_IN_RANGING = 0x0B,
    UCI_SESSION_SET_HUS_CONTROLLER_CONFIG = 0x0C,
    UCI_SESSION_SET_HUS_CONTROLEE_CONFIG = 0x0D
};

enum {
    UCI_SESSION_START = 0x00,
    UCI_SESSION_STOP = 0x01,
    UCI_SESSION_GET_RANGING_COUNT = 0x03,
    UCI_SESSION_DATA_CREDIT_NTF = 0x04,
    UCI_SESSION_DATA_TRANSFER_STATUS_NTF = 0x05,
    UCI_SESSION_LOGICAL_LINK_CREATE = 0x07,
    UCI_SESSION_LOGICAL_LINK_CLOSE = 0x08,
    UCI_SESSION_LOGICAL_LINK_UWBS_CLOSE = 0x09,
    UCI_SESSION_LOGICAL_LINK_UWBS_CREATE = 0x0A,
    UCI_SESSION_LOGICAL_LINK_GET_PARAM = 0x0B
};

enum {
    UCI_DEVICE_STATE_READY = 0x01,
    UCI_DEVICE_STATE_ACTIVE = 0x02,
    UCI_DEVICE_STATE_ERROR = 0xFF
};

enum {
    UCI_DEVICE_CONFIG_DEVICE_STATE = 0x00,
    UCI_DEVICE_CONFIG_LOW_POWER_MODE = 0x01,
    UCI_DEVICE_CONFIG_DEVICE_PAN_ID = 0xA2
};


enum {
    UCI_APP_CONFIG_DEVICE_TYPE = 0x00,
    UCI_APP_CONFIG_STS_CONFIG = 0x02,
    UCI_APP_CONFIG_RANGING_ROUND_USAGE = 0x01,
    UCI_APP_CONFIG_MULTI_NODE_MODE = 0x03,
    UCI_APP_CONFIG_CHANNEL_NUMBER = 0x04,
    UCI_APP_CONFIG_NUMBER_OF_CONTROLEES = 0x05,
    UCI_APP_CONFIG_DEVICE_MAC_ADDRESS = 0x06,
    UCI_APP_CONFIG_DST_MAC_ADDRESS = 0x07,
    UCI_APP_CONFIG_SLOT_DURATION = 0x08,
    UCI_APP_CONFIG_RANGING_INTERVAL = 0x09,
    UCI_APP_CONFIG_AOA_RESULT_REQ = 0x0D,
    UCI_APP_CONFIG_SESSION_INFO_NTF_CONFIG = 0x0E,
    UCI_APP_CONFIG_RNG_DATA_NTF_PROXIMITY_NEAR = 0x0F,
    UCI_APP_CONFIG_RNG_DATA_NTF_PROXIMITY_FAR = 0x10,
    UCI_APP_CONFIG_DEVICE_ROLE = 0x11,
    UCI_APP_CONFIG_RSSI_REPORTING = 0x13,
    UCI_APP_CONFIG_PREAMBLE_CODE_INDEX = 0x14,
    UCI_APP_CONFIG_SFD_ID = 0x15,
    UCI_APP_CONFIG_PSDU_DATA_RATE = 0x16,
    UCI_APP_CONFIG_PREAMBLE_DURATION = 0x17,
    UCI_APP_CONFIG_LINK_LAYER_MODE = 0x18,
    UCI_APP_CONFIG_DATA_REPETITION_COUNT = 0x19,
    UCI_APP_CONFIG_RANGING_TIME_STRUCT = 0x1A,
    UCI_APP_CONFIG_SLOTS_PER_RR = 0x1B,
    UCI_APP_CONFIG_RESPONDER_SLOT_INDEX = 0x1E,
    UCI_APP_CONFIG_CAP_SIZE_RANGE = 0x20,
    UCI_APP_CONFIG_SCHEDULED_MODE = 0x22,
    UCI_APP_CONFIG_KEY_ROTATION = 0x23,
    UCI_APP_CONFIG_KEY_ROTATION_RATE = 0x24,
    UCI_APP_CONFIG_BLOCK_STRIDE_LENGTH = 0x2D,
    UCI_APP_CONFIG_PRF_MODE = 0x1F,
    UCI_APP_CONFIG_MAC_ADDRESS_MODE = 0x26,
    UCI_APP_CONFIG_STATIC_STS_IV = 0x28,
    UCI_APP_CONFIG_NUMBER_OF_STS_SEGMENTS = 0x29,
    UCI_APP_CONFIG_MAX_RR_RETRY = 0x2A,
    UCI_APP_CONFIG_RESULT_REPORT_CONFIG = 0x2E,
    UCI_APP_CONFIG_MAX_NUMBER_OF_MEASUREMENTS = 0x32,
    UCI_APP_CONFIG_STS_LENGTH = 0x35,
    UCI_APP_CONFIG_SESSION_KEY = 0x45,
    UCI_APP_CONFIG_SUBSESSION_KEY = 0x46
};

enum {
    UCI_DEVICE_TYPE_CONTROLEE = 0x00,
    UCI_DEVICE_TYPE_CONTROLLER = 0x01
};

enum {
    UCI_DEVICE_ROLE_RESPONDER = 0x00,
    UCI_DEVICE_ROLE_INITIATOR = 0x01,
    UCI_DEVICE_ROLE_ADVERTISER = 0x05,
    UCI_DEVICE_ROLE_OBSERVER = 0x06,
    UCI_DEVICE_ROLE_DT_ANCHOR = 0x07,
    UCI_DEVICE_ROLE_DT_TAG = 0x08
};

enum {
    UCI_MAC_ADDRESS_MODE_SHORT = 0x00,
    UCI_MAC_ADDRESS_MODE_EXTENDED = 0x01
};

enum {
    UCI_SCHEDULED_MODE_CONTENTION_BASED = 0x00,
    UCI_SCHEDULED_MODE_TIME_SCHEDULED = 0x01,
    UCI_SCHEDULED_MODE_HYBRID = 0x02
};

enum {
    UCI_SESSION_TYPE_RANGING = 0x00,
    UCI_SESSION_TYPE_DATA    = 0x01,
    UCI_SESSION_TYPE_RADAR   = 0xA1,
    UCI_SESSION_TYPE_TEST    = 0xD0
};

enum {
    UCI_SESSION_STATE_INIT = 0x00,
    UCI_SESSION_STATE_DEINIT = 0x01,
    UCI_SESSION_STATE_ACTIVE = 0x02,
    UCI_SESSION_STATE_IDLE = 0x03
};

enum {
    UCI_SESSION_REASON_STATE_CHANGE_WITH_SESSION_MANAGEMENT_COMMANDS = 0x00,
    UCI_SESSION_REASON_MAX_NUMBER_OF_MEASUREMENTS_REACHED = 0x02,
    UCI_SESSION_REASON_ERROR_SLOT_LENGTH_NOT_SUPPORTED = 0x20,
    UCI_SESSION_REASON_ERROR_INSUFFICIENT_SLOTS_PER_RR = 0x21,
    UCI_SESSION_REASON_ERROR_MAC_ADDRESS_MODE_NOT_SUPPORTED = 0x22,
    UCI_SESSION_REASON_ERROR_INVALID_RANGING_INTERVAL = 0x23,
    UCI_SESSION_REASON_ERROR_INVALID_STS_CONFIG = 0x24,
    UCI_SESSION_REASON_ERROR_INVALID_PREAMBLE_CODE_INDEX = 0x2C,
    UCI_SESSION_REASON_ERROR_INVALID_SFD_ID = 0x2D,
    UCI_SESSION_REASON_ERROR_INVALID_PSDU_DATA_RATE = 0x2E,
    UCI_SESSION_REASON_ERROR_INVALID_PREAMBLE_DURATION = 0x30,
    UCI_SESSION_REASON_ERROR_INVALID_STS_LENGTH = 0x31,
    UCI_SESSION_REASON_ERROR_INVALID_NUM_OF_CONTROLEES = 0x33,
    UCI_SESSION_REASON_ERROR_INVALID_DST_ADDRESS_LIST = 0x35,
    UCI_SESSION_REASON_ERROR_INVALID_RESULT_REPORT_CONFIG = 0x37,
    UCI_SESSION_REASON_ERROR_INVALID_RANGING_ROUND_USAGE = 0x39,
    UCI_SESSION_REASON_ERROR_INVALID_MULTI_NODE_MODE = 0x3A,
    UCI_SESSION_REASON_ERROR_REF_UWB_SESSION_DOES_NOT_EXIST = 0x3C,
    UCI_SESSION_REASON_ERROR_REF_UWB_SESSION_RANGING_DURATION_MISMATCH = 0x3D,
    UCI_SESSION_REASON_ERROR_REF_UWB_SESSION_INVALID_OFFSET_TIME = 0x3E,
    UCI_SESSION_REASON_ERROR_REF_UWB_SESSION_LOST = 0x3F,
    UCI_SESSION_REASON_ERROR_INVALID_CAP_SIZE_RANGE = 0xFA
};

enum {
    UCI_MULTICAST_ACTION_ADD = 0x00,
    UCI_MULTICAST_ACTION_REMOVE = 0x01,
    UCI_MULTICAST_ACTION_ADD_SHORT_KEY = 0x02,
    UCI_MULTICAST_ACTION_ADD_LONG_KEY = 0x03
};

enum {
    UCI_DATA_TRANSFER_STATUS_REPETITION_OK = 0x00,
    UCI_DATA_TRANSFER_STATUS_OK = 0x01,
    UCI_DATA_TRANSFER_STATUS_ERROR_DATA_TRANSFER = 0x02,
    UCI_DATA_TRANSFER_STATUS_ERROR_NO_CREDIT_AVAILABLE = 0x03,
    UCI_DATA_TRANSFER_STATUS_ERROR_REJECTED = 0x04,
    UCI_DATA_TRANSFER_STATUS_SESSION_TYPE_NOT_SUPPORTED = 0x05,
    UCI_DATA_TRANSFER_STATUS_ERROR_DATA_TRANSFER_IS_ONGOING = 0x06,
    UCI_DATA_TRANSFER_STATUS_INVALID_FORMAT = 0x07
};

#endif
