#ifndef UCI_SIM_SPEC_H
#define UCI_SIM_SPEC_H

#include <stddef.h>
#include <stdint.h>

#define UCI_SIM_HEADER_SIZE 4U
#define UCI_SIM_MAX_PAYLOAD 1024U
#define UCI_SIM_MAX_PACKET (UCI_SIM_HEADER_SIZE + UCI_SIM_MAX_PAYLOAD)
#define UCI_SIM_MAX_SESSIONS 8U
#define UCI_SIM_MAX_MULTICAST_ENTRIES 8U
#define UCI_SIM_MAX_LOGICAL_LINKS 8U
#define UCI_SIM_MAX_DT_ROUNDS 32U

enum {
    UCI_MT_DATA = 0x0,
    UCI_MT_COMMAND = 0x1,
    UCI_MT_RESPONSE = 0x2,
    UCI_MT_NOTIFICATION = 0x3
};

enum {
    UCI_DATA_PACKET_FORMAT_SEND = 0x01
};

enum {
    UCI_PBF_COMPLETE = 0x0,
    UCI_PBF_NOT_COMPLETE = 0x1
};

enum {
    UCI_GID_CORE = 0x00,
    UCI_GID_SESSION_CONFIG = 0x01,
    UCI_GID_SESSION_CONTROL = 0x02
};

enum {
    UCI_STATUS_OK = 0x00,
    UCI_STATUS_REJECTED = 0x01,
    UCI_STATUS_FAILED = 0x02,
    UCI_STATUS_SYNTAX_ERROR = 0x03,
    UCI_STATUS_INVALID_PARAM = 0x04,
    UCI_STATUS_INVALID_RANGE = 0x05,
    UCI_STATUS_INVALID_MSG_SIZE = 0x06,
    UCI_STATUS_UNKNOWN_GID = 0x07,
    UCI_STATUS_UNKNOWN_OID = 0x08,
    UCI_STATUS_MULTICAST_LIST_FULL = 0x17,
    UCI_STATUS_ADDRESS_NOT_FOUND = 0x18,
    UCI_STATUS_ADDRESS_ALREADY_PRESENT = 0x19
};

enum {
    UCI_CORE_DEVICE_RESET = 0x00,
    UCI_CORE_DEVICE_STATUS_NTF = 0x01,
    UCI_CORE_DEVICE_INFO = 0x02,
    UCI_CORE_GET_CAPS_INFO = 0x03,
    UCI_CORE_SET_CONFIG = 0x04,
    UCI_CORE_GET_CONFIG = 0x05,
    UCI_CORE_GENERIC_ERROR = 0x07,
    UCI_CORE_QUERY_UWBS_TIMESTAMP = 0x08
};

enum {
    UCI_SESSION_INIT = 0x00,
    UCI_SESSION_DEINIT = 0x01,
    UCI_SESSION_STATUS_NTF = 0x02,
    UCI_SESSION_SET_APP_CONFIG = 0x03,
    UCI_SESSION_GET_APP_CONFIG = 0x04,
    UCI_SESSION_GET_COUNT = 0x05,
    UCI_SESSION_GET_STATE = 0x06,
    UCI_SESSION_UPDATE_CONTROLLER_MULTICAST_LIST = 0x07,
    UCI_SESSION_UPDATE_DT_ANCHOR_RANGING_ROUNDS = 0x08,
    UCI_SESSION_UPDATE_DT_TAG_RANGING_ROUNDS = 0x09,
    UCI_SESSION_DATA_TRANSFER_PHASE_CONFIG = 0x0E,
    UCI_SESSION_QUERY_DATA_SIZE_IN_RANGING = 0x0B,
    UCI_SESSION_SET_HUS_CONTROLLER_CONFIG = 0x0C,
    UCI_SESSION_SET_HUS_CONTROLEE_CONFIG = 0x0D
};

enum {
    UCI_SESSION_START = 0x00,
    UCI_SESSION_STOP = 0x01,
    UCI_SESSION_GET_RANGING_COUNT = 0x03,
    UCI_SESSION_DATA_CREDIT_NTF = 0x04,
    UCI_SESSION_DATA_TRANSFER_STATUS_NTF = 0x05,
    UCI_SESSION_LOGICAL_LINK_CREATE = 0x07,
    UCI_SESSION_LOGICAL_LINK_CLOSE = 0x08,
    UCI_SESSION_LOGICAL_LINK_UWBS_CLOSE = 0x09,
    UCI_SESSION_LOGICAL_LINK_UWBS_CREATE = 0x0A,
    UCI_SESSION_LOGICAL_LINK_GET_PARAM = 0x0B
};

enum {
    UCI_DEVICE_STATE_READY = 0x01,
    UCI_DEVICE_STATE_ACTIVE = 0x02,
    UCI_DEVICE_STATE_ERROR = 0xFF
};

enum {
    UCI_DEVICE_CONFIG_DEVICE_STATE = 0x00,
    UCI_DEVICE_CONFIG_LOW_POWER_MODE = 0x01,
    UCI_DEVICE_CONFIG_DEVICE_PAN_ID = 0xA2
};


enum {
    UCI_APP_CONFIG_DEVICE_TYPE = 0x00,
    UCI_APP_CONFIG_STS_CONFIG = 0x02,
    UCI_APP_CONFIG_RANGING_ROUND_USAGE = 0x01,
    UCI_APP_CONFIG_MULTI_NODE_MODE = 0x03,
    UCI_APP_CONFIG_NUMBER_OF_CONTROLEES = 0x05,
    UCI_APP_CONFIG_DST_MAC_ADDRESS = 0x07,
    UCI_APP_CONFIG_RANGING_INTERVAL = 0x09,
    UCI_APP_CONFIG_AOA_RESULT_REQ = 0x0D,
    UCI_APP_CONFIG_SESSION_INFO_NTF_CONFIG = 0x0E,
    UCI_APP_CONFIG_RNG_DATA_NTF_PROXIMITY_NEAR = 0x0F,
    UCI_APP_CONFIG_RNG_DATA_NTF_PROXIMITY_FAR = 0x10,
    UCI_APP_CONFIG_DEVICE_ROLE = 0x11,
    UCI_APP_CONFIG_RSSI_REPORTING = 0x13,
    UCI_APP_CONFIG_STATIC_STS_IV = 0x28,
    UCI_APP_CONFIG_RESULT_REPORT_CONFIG = 0x2E,
    UCI_APP_CONFIG_SESSION_KEY = 0x45,
    UCI_APP_CONFIG_SUBSESSION_KEY = 0x46
};

enum {
    UCI_DEVICE_TYPE_CONTROLEE = 0x00,
    UCI_DEVICE_TYPE_CONTROLLER = 0x01
};

enum {
    UCI_DEVICE_ROLE_RESPONDER = 0x00,
    UCI_DEVICE_ROLE_INITIATOR = 0x01,
    UCI_DEVICE_ROLE_ADVERTISER = 0x05,
    UCI_DEVICE_ROLE_OBSERVER = 0x06,
    UCI_DEVICE_ROLE_DT_ANCHOR = 0x07,
    UCI_DEVICE_ROLE_DT_TAG = 0x08
};

enum {
    UCI_SESSION_TYPE_RANGING = 0x00
};

enum {
    UCI_SESSION_STATE_INIT = 0x00,
    UCI_SESSION_STATE_DEINIT = 0x01,
    UCI_SESSION_STATE_ACTIVE = 0x02,
    UCI_SESSION_STATE_IDLE = 0x03
};

enum {
    UCI_SESSION_REASON_STATE_CHANGE_WITH_SESSION_MANAGEMENT_COMMANDS = 0x00,
    UCI_SESSION_REASON_ERROR_INVALID_RANGING_INTERVAL = 0x23,
    UCI_SESSION_REASON_ERROR_INVALID_STS_CONFIG = 0x24,
    UCI_SESSION_REASON_ERROR_INVALID_NUM_OF_CONTROLEES = 0x33,
    UCI_SESSION_REASON_ERROR_INVALID_DST_ADDRESS_LIST = 0x35,
    UCI_SESSION_REASON_ERROR_INVALID_RESULT_REPORT_CONFIG = 0x37,
    UCI_SESSION_REASON_ERROR_INVALID_RANGING_ROUND_USAGE = 0x39,
    UCI_SESSION_REASON_ERROR_INVALID_MULTI_NODE_MODE = 0x3A
};

enum {
    UCI_MULTICAST_ACTION_ADD = 0x00,
    UCI_MULTICAST_ACTION_REMOVE = 0x01,
    UCI_MULTICAST_ACTION_ADD_SHORT_KEY = 0x02,
    UCI_MULTICAST_ACTION_ADD_LONG_KEY = 0x03
};

enum {
    UCI_DATA_TRANSFER_STATUS_REPETITION_OK = 0x00,
    UCI_DATA_TRANSFER_STATUS_OK = 0x01,
    UCI_DATA_TRANSFER_STATUS_ERROR_DATA_TRANSFER = 0x02,
    UCI_DATA_TRANSFER_STATUS_ERROR_NO_CREDIT_AVAILABLE = 0x03,
    UCI_DATA_TRANSFER_STATUS_ERROR_REJECTED = 0x04,
    UCI_DATA_TRANSFER_STATUS_SESSION_TYPE_NOT_SUPPORTED = 0x05,
    UCI_DATA_TRANSFER_STATUS_ERROR_DATA_TRANSFER_IS_ONGOING = 0x06,
    UCI_DATA_TRANSFER_STATUS_INVALID_FORMAT = 0x07
};

const char* uci_sim_status_name(uint8_t status);
const char* uci_sim_gid_name(uint8_t gid);

#endif
